//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplication2.ServiceReference1.HelloWorldResponse HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name file from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readBooks", ReplyAction="*")]
        WebApplication2.ServiceReference1.readBooksResponse readBooks(WebApplication2.ServiceReference1.readBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/readBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.readBooksResponse> readBooksAsync(WebApplication2.ServiceReference1.readBooksRequest request);
        
        // CODEGEN: Generating message contract since element name line from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/writeBooks", ReplyAction="*")]
        WebApplication2.ServiceReference1.writeBooksResponse writeBooks(WebApplication2.ServiceReference1.writeBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/writeBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.writeBooksResponse> writeBooksAsync(WebApplication2.ServiceReference1.writeBooksRequest request);
        
        // CODEGEN: Generating message contract since element name file from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteBooks", ReplyAction="*")]
        WebApplication2.ServiceReference1.deleteBooksResponse deleteBooks(WebApplication2.ServiceReference1.deleteBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.deleteBooksResponse> deleteBooksAsync(WebApplication2.ServiceReference1.deleteBooksRequest request);
        
        // CODEGEN: Generating message contract since element name file from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isExist", ReplyAction="*")]
        WebApplication2.ServiceReference1.isExistResponse isExist(WebApplication2.ServiceReference1.isExistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isExist", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.isExistResponse> isExistAsync(WebApplication2.ServiceReference1.isExistRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplication2.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplication2.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readBooks", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.readBooksRequestBody Body;
        
        public readBooksRequest() {
        }
        
        public readBooksRequest(WebApplication2.ServiceReference1.readBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class readBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file;
        
        public readBooksRequestBody() {
        }
        
        public readBooksRequestBody(string file) {
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class readBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="readBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.readBooksResponseBody Body;
        
        public readBooksResponse() {
        }
        
        public readBooksResponse(WebApplication2.ServiceReference1.readBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class readBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.ServiceReference1.ArrayOfString readBooksResult;
        
        public readBooksResponseBody() {
        }
        
        public readBooksResponseBody(WebApplication2.ServiceReference1.ArrayOfString readBooksResult) {
            this.readBooksResult = readBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeBooks", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.writeBooksRequestBody Body;
        
        public writeBooksRequest() {
        }
        
        public writeBooksRequest(WebApplication2.ServiceReference1.writeBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class writeBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string line;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        public writeBooksRequestBody() {
        }
        
        public writeBooksRequestBody(string line, string file) {
            this.line = line;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class writeBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="writeBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.writeBooksResponseBody Body;
        
        public writeBooksResponse() {
        }
        
        public writeBooksResponse(WebApplication2.ServiceReference1.writeBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class writeBooksResponseBody {
        
        public writeBooksResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteBooks", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.deleteBooksRequestBody Body;
        
        public deleteBooksRequest() {
        }
        
        public deleteBooksRequest(WebApplication2.ServiceReference1.deleteBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int bookID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        public deleteBooksRequestBody() {
        }
        
        public deleteBooksRequestBody(int bookID, string file) {
            this.bookID = bookID;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.deleteBooksResponseBody Body;
        
        public deleteBooksResponse() {
        }
        
        public deleteBooksResponse(WebApplication2.ServiceReference1.deleteBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteBooksResponseBody {
        
        public deleteBooksResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExist", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.isExistRequestBody Body;
        
        public isExistRequest() {
        }
        
        public isExistRequest(WebApplication2.ServiceReference1.isExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int bookID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string file;
        
        public isExistRequestBody() {
        }
        
        public isExistRequestBody(int bookID, string file) {
            this.bookID = bookID;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication2.ServiceReference1.isExistResponseBody Body;
        
        public isExistResponse() {
        }
        
        public isExistResponse(WebApplication2.ServiceReference1.isExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isExistResult;
        
        public isExistResponseBody() {
        }
        
        public isExistResponseBody(bool isExistResult) {
            this.isExistResult = isExistResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.ServiceReference1.WebService1Soap>, WebApplication2.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.HelloWorldResponse WebApplication2.ServiceReference1.WebService1Soap.HelloWorld(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            WebApplication2.ServiceReference1.HelloWorldResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> WebApplication2.ServiceReference1.WebService1Soap.HelloWorldAsync(WebApplication2.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplication2.ServiceReference1.HelloWorldRequest inValue = new WebApplication2.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplication2.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.readBooksResponse WebApplication2.ServiceReference1.WebService1Soap.readBooks(WebApplication2.ServiceReference1.readBooksRequest request) {
            return base.Channel.readBooks(request);
        }
        
        public WebApplication2.ServiceReference1.ArrayOfString readBooks(string file) {
            WebApplication2.ServiceReference1.readBooksRequest inValue = new WebApplication2.ServiceReference1.readBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.readBooksRequestBody();
            inValue.Body.file = file;
            WebApplication2.ServiceReference1.readBooksResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).readBooks(inValue);
            return retVal.Body.readBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.readBooksResponse> WebApplication2.ServiceReference1.WebService1Soap.readBooksAsync(WebApplication2.ServiceReference1.readBooksRequest request) {
            return base.Channel.readBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.readBooksResponse> readBooksAsync(string file) {
            WebApplication2.ServiceReference1.readBooksRequest inValue = new WebApplication2.ServiceReference1.readBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.readBooksRequestBody();
            inValue.Body.file = file;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).readBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.writeBooksResponse WebApplication2.ServiceReference1.WebService1Soap.writeBooks(WebApplication2.ServiceReference1.writeBooksRequest request) {
            return base.Channel.writeBooks(request);
        }
        
        public void writeBooks(string line, string file) {
            WebApplication2.ServiceReference1.writeBooksRequest inValue = new WebApplication2.ServiceReference1.writeBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.writeBooksRequestBody();
            inValue.Body.line = line;
            inValue.Body.file = file;
            WebApplication2.ServiceReference1.writeBooksResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).writeBooks(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.writeBooksResponse> WebApplication2.ServiceReference1.WebService1Soap.writeBooksAsync(WebApplication2.ServiceReference1.writeBooksRequest request) {
            return base.Channel.writeBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.writeBooksResponse> writeBooksAsync(string line, string file) {
            WebApplication2.ServiceReference1.writeBooksRequest inValue = new WebApplication2.ServiceReference1.writeBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.writeBooksRequestBody();
            inValue.Body.line = line;
            inValue.Body.file = file;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).writeBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.deleteBooksResponse WebApplication2.ServiceReference1.WebService1Soap.deleteBooks(WebApplication2.ServiceReference1.deleteBooksRequest request) {
            return base.Channel.deleteBooks(request);
        }
        
        public void deleteBooks(int bookID, string file) {
            WebApplication2.ServiceReference1.deleteBooksRequest inValue = new WebApplication2.ServiceReference1.deleteBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.deleteBooksRequestBody();
            inValue.Body.bookID = bookID;
            inValue.Body.file = file;
            WebApplication2.ServiceReference1.deleteBooksResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).deleteBooks(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.deleteBooksResponse> WebApplication2.ServiceReference1.WebService1Soap.deleteBooksAsync(WebApplication2.ServiceReference1.deleteBooksRequest request) {
            return base.Channel.deleteBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.deleteBooksResponse> deleteBooksAsync(int bookID, string file) {
            WebApplication2.ServiceReference1.deleteBooksRequest inValue = new WebApplication2.ServiceReference1.deleteBooksRequest();
            inValue.Body = new WebApplication2.ServiceReference1.deleteBooksRequestBody();
            inValue.Body.bookID = bookID;
            inValue.Body.file = file;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).deleteBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.ServiceReference1.isExistResponse WebApplication2.ServiceReference1.WebService1Soap.isExist(WebApplication2.ServiceReference1.isExistRequest request) {
            return base.Channel.isExist(request);
        }
        
        public bool isExist(int bookID, string file) {
            WebApplication2.ServiceReference1.isExistRequest inValue = new WebApplication2.ServiceReference1.isExistRequest();
            inValue.Body = new WebApplication2.ServiceReference1.isExistRequestBody();
            inValue.Body.bookID = bookID;
            inValue.Body.file = file;
            WebApplication2.ServiceReference1.isExistResponse retVal = ((WebApplication2.ServiceReference1.WebService1Soap)(this)).isExist(inValue);
            return retVal.Body.isExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.ServiceReference1.isExistResponse> WebApplication2.ServiceReference1.WebService1Soap.isExistAsync(WebApplication2.ServiceReference1.isExistRequest request) {
            return base.Channel.isExistAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.ServiceReference1.isExistResponse> isExistAsync(int bookID, string file) {
            WebApplication2.ServiceReference1.isExistRequest inValue = new WebApplication2.ServiceReference1.isExistRequest();
            inValue.Body = new WebApplication2.ServiceReference1.isExistRequestBody();
            inValue.Body.bookID = bookID;
            inValue.Body.file = file;
            return ((WebApplication2.ServiceReference1.WebService1Soap)(this)).isExistAsync(inValue);
        }
    }
}
